// src/models/Complaint.js
// The central model of the platform.
// Complaint history is embedded as a subdocument array (not a separate collection).
// This keeps all timeline events atomically consistent with the complaint document.

import mongoose from 'mongoose';

// ---------------------------------------------------------------------------
// Embedded history event subdocument
// Each status change, assignment, resolution, and verification produces one
// history event. Events are append-only and never deleted.
// ---------------------------------------------------------------------------
const historyEventSchema = new mongoose.Schema(
  {
    eventType: {
      type: String,
      required: true,
      enum: [
        'CREATED',
        'ASSIGNED',
        'STATUS_CHANGED',
        'RESOLUTION_CREATED',
        'RESOLVED',
        'VERIFIED',
        'REOPENED',
        'CLOSED',
      ],
    },
    description: {
      type: String,
      required: true,
    },
    // ObjectId of the user who triggered this event. Null for system events.
    performedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    // Denormalised name so the timeline renders correctly even if the user is
    // later deleted or renamed.
    performedByName: {
      type: String,
      default: null,
    },
    eventAt: {
      type: Date,
      default: Date.now,
    },
  },
  { _id: false } // subdocuments don't need their own _id
);

// ---------------------------------------------------------------------------
// Main Complaint schema
// ---------------------------------------------------------------------------
const complaintSchema = new mongoose.Schema({
  // Human-readable reference number, e.g. "CP-1001".
  // Generated by complaintHelpers.js before saving.
  reference: {
    type: String,
    required: true,
    unique: true,
    index: true,
  },

  title: {
    type: String,
    required: true,
    trim: true,
    minlength: 3,
  },

  // Category label (e.g. "Roads & Transport").
  // Determined by keyword routing or citizen selection.
  category: {
    type: String,
    required: true,
    trim: true,
    minlength: 2,
  },

  description: {
    type: String,
    required: true,
    trim: true,
    minlength: 10,
  },

  // Human-readable location address entered by the citizen.
  location: {
    type: String,
    required: true,
    trim: true,
  },

  // GPS coordinates validated by the India boundary geofence (complaintHelpers.js).
  latitude: {
    type: Number,
    required: true,
    min: -90,
    max: 90,
  },
  longitude: {
    type: Number,
    required: true,
    min: -180,
    max: 180,
  },

  // Optional photo proof stored as a Base64 data URL string.
  // Null when no photo is attached.
  photoData: {
    type: String,
    default: null,
  },

  // Complaint lifecycle status.
  // Default is ASSIGNED because auto-assignment runs before the document is saved.
  status: {
    type: String,
    required: true,
    enum: [
      'PENDING',
      'ASSIGNED',
      'IN_PROGRESS',
      'RESOLVED',
      'REOPENED',
      'CLOSED',
      'REJECTED',
    ],
    default: 'ASSIGNED',
  },

  // The citizen who submitted this complaint.
  citizen: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },

  // The department this complaint was routed to (keyword engine or citizen choice).
  department: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Department',
    required: true,
    index: true,
  },

  // The staff member auto-assigned to handle this complaint.
  // Null if no eligible staff exists in the department.
  assignedStaff: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null,
    index: true,
  },

  // Internal staff remarks about the complaint (optional, added during handling).
  remarks: {
    type: String,
    default: null,
  },

  // Resolution note — required before a complaint can be marked RESOLVED.
  resolution: {
    type: String,
    default: null,
  },

  // Citizen verification of the resolution.
  verificationStatus: {
    type: String,
    required: true,
    enum: ['PENDING', 'ACCEPTED', 'REJECTED'],
    default: 'PENDING',
  },

  // Timestamp when the citizen verified the resolution.
  verifiedAt: {
    type: Date,
    default: null,
  },

  // Reason the citizen rejected the resolution (required when reopening).
  reopenReason: {
    type: String,
    default: null,
  },

  // Embedded timeline — all lifecycle events in chronological order.
  history: [historyEventSchema],

  createdAt: {
    type: Date,
    default: Date.now,
    index: true,  // used for age-based sorting and emerging-issues time windows
  },

  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

export default mongoose.model('Complaint', complaintSchema);
